name: Alpha Build Typewriter

on:
  push:
    paths:
      - 'app/**'
      - 'extensions/**'
      - 'engine/**'
      - 'module-plugin/**'
  pull_request:
    paths:
      - 'app/**'
      - 'extensions/**'
      - 'engine/**'
      - 'module-plugin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}
          cache-cleanup: always
          build-scan-publish: false
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Build Engine
        uses: ./.github/actions/build-engine

#  ----------------------------------------------------------------------------------------------------
      - name: Build Extensions
        working-directory: ./extensions
        run: ./gradlew test buildRelease --scan --stacktrace --warning-mode all

      - name: Upload Jars as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Typewriter-Alpha-Builds
          path: |
            jars/engine/*.jar
            jars/extensions/*.jar
          retention-days: 3
          if-no-files-found: error
